chanages

diff --git a/install-basics b/install-basics
--- a/install-basics
+++ b/install-basics
@@ -1,5 +1,7 @@
 #!/bin/bash
-
+GO_VER=1.22.0
+NODE_VER=21
+PG_VER=15
 # Update package list
 sudo apt-get update
 
@@ -8,31 +10,58 @@ sudo apt-get install -y curl
 
 # Install zip and unzip
 sudo apt-get install -y zip unzip
-echo "Zip and unzip tools have been installed successfully!"
+echo "============== Zip and unzip tools have been installed successfully! =============== "
 
-# Install fish shell and oh-my-fish
-sudo apt-add-repository -y ppa:fish-shell/release-3
-sudo apt-get update
-sudo apt-get install -y fish
-curl -L https://get.oh-my.fish | fish
-echo "Fish shell and oh-my-fish have been installed successfully!"
+
 
 # Install Git
 sudo apt-get install -y git
 # Configure git.name and git.email
 git config --global user.name "tigawanna"
 git config --global user.email "denniskinuthiaw@gmail.com"
-echo "Git has been installed successfully!"
+echo "============== Git has been installed successfully! =============="
 
 # Install SQLite
 sudo apt-get install -y sqlite3
-echo "SQLite has been installed successfully!"
+echo "============== SQLite has been installed successfully! =============="
 
 # Install PostgreSQL 15
 sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
 wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null
-sudo apt update
+# Install PostgreSQL
 sudo apt install postgresql postgresql-client -y
+echo "============== PostgreSQL 15 has been installed successfully! =============="
+
+# Add PostgreSQL repository
+# echo "Adding PostgreSQL $PG_VER repository..."
+# if ! sudo sh -c "echo \"deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main\" > /etc/apt/sources.list.d/pgdg.list"; then
+#   echo "Error: Failed to add repository. Please check your privileges and network connection."
+#   exit 1
+# fi
+
+# # Import GPG key using apt-key (recommended)
+# echo "Importing PostgreSQL GPG key..."
+# if ! sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ACCC4CF8; then
+#   echo "Error: Failed to import GPG key. Please check your network connection."
+#   exit 1
+# fi
+
+# # Update package lists
+# echo "Updating package lists..."
+# if ! sudo apt update; then
+#   echo "Error: Failed to update package lists."
+#   exit 1
+# fi
+
+# # Install PostgreSQL server and client packages
+# echo "Installing PostgreSQL $PG_VER..."
+# if ! sudo apt install postgresql-$PG_VER postgresql-$PG_VER-client -y; then
+#   echo "Error: Failed to install PostgreSQL packages."
+#   exit 1
+# fi
+
+# # Success message
+# echo "============== PostgreSQL $PG_VER has been installed successfully! =============="
 
 # Install Node.js 20 using nvm
 # Install NVM (Node Version Manager)
@@ -40,24 +69,89 @@ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
 # Activate NVM
 source ~/.nvm/nvm.sh
 # Install Node.js 20
-nvm install 20
+nvm install $NODE_VER
 # Set Node.js 20 as the default version
-nvm alias default 20
-echo "Node.js 20 has been installed successfully!"
+nvm alias default $NODE_VER
+echo "============== Node.js $NODE_VER has been installed successfully! =============="
 
 
 # Install bun
 curl -fsSL https://bun.sh/install | bash
-echo "Bun has been installed successfully!"
+echo "============== Bun has been installed successfully! =============="
 
 # Install deno
 curl -fsSL https://deno.land/x/install/install.sh | sh
-echo "Deno has been installed successfully!"
+echo "============== Deno has been installed successfully! =============="
 
 # Install Flyctl
 curl -sL https://cli.fly.io/install.sh | sh
-echo "Flyctl has been installed successfully!"
+echo "============== Flyctl has been installed successfully! =============="
+
+sudo wget -c https://golang.org/dl/go$GO_VER.linux-amd64.tar.gz
+sudo rm -rf /usr/local/go
+sudo tar -C /usr/local  -xvzf go$GO_VER.linux-amd64.tar.gz
+sudo rm -rf go$GO_VER.linux-amd64.tar.gz
+echo "============== Go has been installed successfully! =============="
+
+
+echo `
+# add below variables 
+# better ls colors
+LS_COLORS='ex=01;91:rs=0:di=1;33:ln=01;35:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=01;35;40:st=37;44:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;35:*.au=00;35:*.flac=00;35:*.mid=00;35:*.midi=00;35:*.mka=00;35:*.mp3=00;35:*.mpc=00;35:*.ogg=00;35:*.ra=00;35:*.wav=00;35:*.axa=00;35:*.oga=00;35:*.spx=00;35:*.xspf=00;35:';
+export LS_COLORS
+# go
+export GOROOT=/usr/local/go
+export PATH=$PATH:$GOROOT/bin
+# go
+export GOPATH=/home/dennis/golibs
+export PATH=$PATH:$GOPATH/bin
+
+# nvm
+export NVM_DIR="$HOME/.nvm"
+[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
+
+# bun
+export BUN_INSTALL="$HOME/.bun"
+export PATH=$BUN_INSTALL/bin:$PATH
+
+# deno
+export DENO_INSTALL="/home/dennis/.deno"
+export PATH="$DENO_INSTALL/bin:$PATH"
+`>> "~/.bashrc"
+
+
 
 # add fish-nvm
 # omf install https://github.com/fabioantunes/fish-nvm
 # omf install https://github.com/edc/bass
+
+# Install fish shell and oh-my-fish
+sudo apt-add-repository -y ppa:fish-shell/release-3
+sudo apt-get update
+sudo apt-get install -y fish
+echo`
+# Commands to run in interactive sessions can go here
+set -x LS_COLORS 'ex=01;91:rs=0:di=1;33:ln=01;35:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=01;35;40:st=37;44:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;35:*.au=00;35:*.flac=00;35:*.mid=00;35:*.midi=00;35:*.mka=00;35:*.mp3=00;35:*.mpc=00;35:*.ogg=00;35:*.ra=00;35:*.wav=00;35:*.axa=00;35:*.oga=00;35:*.spx=00;35:*.xspf=00;35:';
+
+
+set -x GOROOT /usr/local/go
+set -x  PATH $PATH:$GOROOT/bin
+
+set -x GOPATH /home/dennis/golibs
+set -x  PATH $PATH:$GOPATH/bin
+
+
+
+# bun
+set -x  BUN_INSTALL "$HOME/.bun"
+set -x  PATH $BUN_INSTALL/bin:$PATH
+
+# deno
+set -x  DENO_INSTALL "/home/dennis/.deno"
+set -x  PATH "$DENO_INSTALL/bin:$PATH"
+`>>"~/.config/fish/config.fish"
+
+
+curl -L https://get.oh-my.fish | fish
+echo "============== Fish shell and oh-my-fish have been installed successfully! =============="
